config/routes.rb
Rails.application.routes.draw do
  
  resources :brands
  resources :categories
  resources :users
  resources :orders
  resources :articles
  resources :line_items
  resources :carts
  resources :products
  resources :sessions, only: [:new, :create, :destroy]
  
  match '/signup',   to: 'users#new',             via: 'get'
  match '/signin',   to: 'sessions#new',          via: 'get'
  match '/signout',  to: 'sessions#destroy',      via: 'delete'
  
  match '/contacts', to: 'static_pages#contacts', via: 'get'

  resources :products do
    get :who_bought, on: :member
  end

  get 'store/index'
  root to: 'store#index'
end

app/models/article.rb
class Article < ActiveRecord::Base  
  belongs_to :category
  
  validates :title, :description, :name, :text, :url, presence: true
  validates :name, uniqueness: true
  validates :url, uniqueness: true
  
  def to_param
    "#{id}-#{url}"
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  include CurrentCart
  before_action :set_cart
  
  http_basic_authenticate_with name: "vitaha", password: "vitaha1978", except: [:index, :show]
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index    
    @articles = Article.paginate(:page => params[:page], :per_page => 2)
    @categories = Category.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @articles = Article.all
    @categories = Category.all
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :description, :name, :text, :url, :img_url, :category_id)
    end
end

app/views/articles/_article.html.erb
<%= link_to article.name, article %>

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control" %>
  </div>  
  <div class="field">
    <%= f.label :img_url %><br>
    <%= f.text_field :img_url, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :text %><br>
    <%= f.text_area :text, class: "form-control", rows: 8 %>
  </div>
  <div class="field">
    <%= f.label :category_id, "Виберіть категорію" %><br>
    <%= f.collection_select :category_id, Category.all, :id, :name, {prompt: "Виберіть категорію"}, {class: "form-control"} %>
  </div>
  <div class="actions"><br>
    <%= f.submit "Зберегти", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Редагування статті</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<%= provide(:description, "Статті сайту") %>
<%= provide(:title, "Статті сайту") %>


<% @articles.each do |article| %>
  <div id="articles" class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">
        <%= link_to article.name, article_path(article) %>
      </h3>
    </div>
    <div class="panel-body">
      <p>
        <%= image_tag(article.img_url, class: "img-thumbnail welly", width: 150) %>
      </p>
      <p>
        <%= truncate(strip_tags(article.text), length: 300) %>
       </p> 
      <div class="pull-right">
        <%= link_to "Детальніше...", article, class: 'pull-right' %>
      </div>
    </div>
  </div>
<% end %>
<%= will_paginate @articles, renderer: BootstrapPagination::Rails %>

<p>
  <%= link_to 'Додати статтю', new_article_path %>
</p>

app/views/articles/new.html.erb
<h1>Нова стаття</h1>

<%= render 'form' %>

<%= link_to 'Повернутися', articles_path %>

app/views/articles/show.html.erb
<% provide( :description, @article.description ) %>
<% provide( :title, @article.title ) %>

<% if notice %>
  <p id="notice"><%= notice %></p>
<% end %>


<div id="article" class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">
      <%= @article.name %>
    </h3>
  </div>
  <div class="panel-body">    
    <%= sanitize(@article.text) %>
  </div>
</div>

<script type="text/javascript" src="//yandex.st/share/share.js"charset="utf-8"></script>
<div class="yashare-auto-init" data-yashareL10n="ru"
         data-yashareQuickServices="vkontakte,facebook,twitter,odnoklassniki,moimir,gplus" data-yashareTheme="counter"></div> 
<br>

<%= link_to 'Назад', articles_path %> |
<%= link_to 'Редагувати', edit_article_path(@article) %> |
<%= link_to 'Видалити', @article, method: :delete, data: { confirm: 'Ви впевнені?' } %>