config/routes.rb
Rails.application.routes.draw do
  
  resources :brands
  resources :categories
  resources :users
  resources :orders
  resources :articles
  resources :line_items
  resources :carts
  resources :products
  resources :sessions, only: [:new, :create, :destroy]
  
  match '/signup',   to: 'users#new',             via: 'get'
  match '/signin',   to: 'sessions#new',          via: 'get'
  match '/signout',  to: 'sessions#destroy',      via: 'delete'
  
  match '/contacts', to: 'static_pages#contacts', via: 'get'

  resources :products do
    get :who_bought, on: :member
  end

  get 'store/index'
  root to: 'store#index'
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :products
  has_many :articles
  
  def to_param
    "#{id}-#{url}"
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  http_basic_authenticate_with name: "vitaha", password: "vitaha1978", except: [:index, :show]
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @categories = Category.all
    @articles = Article.all
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :url)
    end
end

app/views/categories/_category.html.erb
<%= link_to category.name, category %>

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url, class: "form-control"%>
  </div><br>
  <div class="actions">
    <%= f.submit 'Зберегти', class: "btn btn-primary" %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1>Listing categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= category.url %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<% provide( :description, @category.name ) %>
<% provide( :title, @category.name ) %>

<% if notice %>
  <p id="notice"><%= notice %></p>
<% end %>
<h1 class="brand">Категорія: <%= @category.name %></h1>
<% @category.products.each do |product| %>
  <div class="entry">
    <%= image_tag(product.image_url, class: "img-thumbnail", width: 100) %>
    <h3><%= link_to product.title, product %></h3>
    <p>
      <%= truncate(strip_tags(product.description), length: 150) %>
      <%= link_to 'далі...', product %>
    </p>
    <div class="price_line ">
      <span class="brand">
        <%= sprintf("%0.02f", product.price) %> грн.
      </span>      
      <%= button_to 'Додати до корзини', line_items_path(product_id: product),
                       class: "btn btn-primary btn-xs pull-right" %>
    </div>
  </div>
<% end %><br>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>